version: "3.8"
services:
  nginx:
    depends_on:
      - api
      - front
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3500:80"

  front:
    container_name: fronted
    build:
      context: ./app
      dockerfile: Dockerfile.dev

  api:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    restart: on-failure

  worker:
    container_name: worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: on-failure

  postgres:
    image: postgres:14.5
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

  redis:
    image: redis:7
    container_name: redis
