version: "3.8"
services:
  react-app-dev:
    container_name: frontend
    image: angelozdev/react-app-dev:latest
    build:
      context: app
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./app/src:/app/src

  server:
    container_name: backend
    image: angelozdev/server-dev:latest
    build:
      context: server
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    volumes:
      - ./server/src:/server/src
